### ISSUE TITLE
Deconz unstable with version 5.3.6

### ISSUE THREAD

**Issue by PaulAntonDeen** [home-assistant/addons#1463]
When I update Deconz from version 5.3.5 to version 5.3.6 it goes from stable to unstable.
(period of 4 hrs today)
![image](https://user-images.githubusercontent.com/25848961/87434379-b18c4300-c5ea-11ea-8d27-21a54c7217b2.png)
(period of 12 hours on July 2nd) 
![image](https://user-images.githubusercontent.com/25848961/87435185-ad145a00-c5eb-11ea-976f-e8d8856402e0.png)

When the gray vertical bars start I have just upgraded Deconz, then I have a period of intermittent Deconz unavailability (the gray bars) and then I restored the old version from a snapshot and all is stable again.

**Comment by Mimiix** [comment]
Any logs?

**Comment by PaulAntonDeen** [comment]
Nothing in the system log. The Deconz log gets reset when Deconz restarts.

**Comment by Mimiix** [comment]
The HA logging (from the logger) https://www.home-assistant.io/integrations/deconz/#debugging-integration

That should say something.

**Comment by Mimiix** [comment]
TO add to that: What do you have as serial device? dev/tty*?
If you have that, please switch to the full hardware id.

**Comment by PaulAntonDeen** [comment]
I have device: /dev/ttyACM0 in my config since this weekend. So one of these events occured with the full hardware ID setup and one of these with tty version. It does not make a difference there. Where it does make a difference is in which device Deconz thinks it sees. With this tty format it correctly identifies my Conbee 2 whereas with the hardware id it thinks I have a raspbee and it presents the wrong firmware. I've just added the logger component to the config and update deconz zo I should have some logs in an hour or so.

**Comment by Mimiix** [comment]
The Raspbee/conbee II mixup is just a cosmetic issue. I got it on the Todo list on DE's side, which means it should be fixed the next month 15th.

Other than that naming, it's no issue.

**Comment by PaulAntonDeen** [comment]
I see these in the log:
2020-07-15 11:23:47 DEBUG (MainThread) [pydeconz.websocket] Websocket starting
2020-07-15 11:23:47 DEBUG (MainThread) [pydeconz.websocket] Reconnecting to deCONZ in 15.

Then all my automations run:
2020-07-15 11:23:47 INFO (MainThread) [homeassistant.components.automation] Executing Achterkamer kastlicht
2020-07-15 11:23:47 INFO (MainThread) [homeassistant.components.automation] Achterkamer kastlicht: Running script
2020-07-15 11:23:47 INFO (MainThread) [homeassistant.components.automation] Achterkamer kastlicht: Executing step call service
more of this:
2020-07-15 11:24:02 DEBUG (MainThread) [pydeconz.websocket] Websocket starting
2020-07-15 11:24:58 DEBUG (MainThread) [pydeconz.websocket] Websocket running
2020-07-15 11:24:58 DEBUG (MainThread) [pydeconz.websocket] {"config":{"alert":"none","battery":74,"delay":60,"duration":62,"group":"29387","on":true,"reachable":true},"e":"changed","id":"25","r":"sensors","t":"event","uniqueid":"d0:cf:5e:ff:fe:30:77:ab-01-0006"}
2020-07-15 11:24:58 DEBUG (MainThread) [pydeconz.websocket] {"e":"changed","id":"25","r":"sensors","state":{"dark":false,"lastupdated":"2020-07-15T09:24:58.108","presence":true},"t":"event","uniqueid":"d0:cf:5e:ff:fe:30:77:ab-01-0006"}
2020-07-15 11:24:58 DEBUG (MainThread) [pydeconz.websocket] {"e":"changed","id":"26","r":"sensors","state":{"lastupdated":"2020-07-15T09:24:58.160","presence":true},"t":"event","uniqueid":"vpir-1575834879803"}
2020-07-15 11:24:58 DEBUG (MainThread) [pydeconz.websocket] {"attr":{"lastseen":"2020-07-15T09:24:58Z","manufacturername":"FeiBit","modelid":"FNB56-ZSC01LX1.2","name":"Eettafel","swversion":"00000001","type":"Dimmable light","uniqueid":"00:15:8d:00:04:62:6c:ba-01"},"e":"changed","id":"54","r":"lights","t":"event","uniqueid":"00:15:8d:00:04:62:6c:ba-01"}
2020-07-15 11:24:58 DEBUG (MainThread) [pydeconz.websocket] {"attr":{"lastseen":"2020-07-15T09:24:58Z","manufacturername":"IKEA of Sweden","modelid":"TRADFRI bulb GU10 W 400lm","name":"Zolder wc","swversion":"1.2.214","type":"Dimmable light","uniqueid":"d0:cf:5e:ff:fe:ef:2a:f3-01"},"e":"changed","id":"18","r":"lights","t":"event","uniqueid":"d0:cf:5e:ff:fe:ef:2a:f3-01"}
2020-07-15 11:24:58 DEBUG (MainThread) [pydeconz.gateway] Sending "put" "{'on': False}" to "172.30.33.2 /lights/40/state"
2020-07-15 11:24:58 DEBUG (MainThread) [pydeconz.gateway] HTTP request response: [{'success': {'/lights/40/state/on': False}}]
2020-07-15 11:24:59 DEBUG (MainThread) [pydeconz.websocket] {"attr":{"lastseen":"2020-07-15T09:24:59Z","manufacturername":"FeiBit","modelid":"FNB56-ZSC01LX1.2","name":"Eettafel","swversion":"00000001","type":"Dimmable light","uniqueid":"00:15:8d:00:04:62:6c:ba-01"},"e":"changed","id":"54","r":"lights","t":"event","uniqueid":"00:15:8d:00:04:62:6c:ba-01"}
2020-07-15 11:25:00 DEBUG (MainThread) [pydeconz.websocket] {"attr":{"lastseen":"2020-07-15T09:25:00Z","manufacturername":"FeiBit","modelid":"FNB56-ZSC01LX1.2","name":"Eettafel","swversion":"00000001","type":"Dimmable light","uniqueid":"00:15:8d:00:04:62:6c:ba-01"},"e":"changed","id":"54","r":"lights","t":"event","uniqueid":"00:15:8d:00:04:62:6c:ba-01"}
2020-07-15 11:25:02 DEBUG (MainThread) [pydeconz.websocket] {"attr":{"lastseen":"2020-07-15T09:25:02Z","manufacturername":"IKEA of Sweden","modelid":"TRADFRI bulb GU10 W 400lm","name":"Zolder wc","swversion":"1.2.214","type":"Dimmable light","uniqueid":"d0:cf:5e:ff:fe:ef:2a:f3-01"},"e":"changed","id":"18","r":"lights","t":"event","uniqueid":"d0:cf:5e:ff:fe:ef:2a:f3-01"}
2020-07-15 11:25:26 DEBUG (MainThread) [pydeconz.websocket] Websocket starting
2020-07-15 11:25:26 DEBUG (MainThread) [pydeconz.websocket] Reconnecting to deCONZ in 15.

so there is about 3 or 4 cycles of websockets starting and reconnecting and then the normal last-seen status update messages resume.

**Comment by Mimiix** [comment]
That's typical behaviour on the API side when the serial isn't right. Websockets are managed by the client (HA integration at this case). 

However, can you provide me the logs of the deCONZ addon itself?

**Comment by PaulAntonDeen** [comment]
I've changed back to the full hardware id in the config.

Deconz log
13:06:55:619 0x90fd9ffffe6e675e found group 0xFFF0
13:06:55:650 Bind response success for 0x90fd9ffffe6e675e ep: 0x01 cluster: 0x0000
13:06:55:650 skip configure report for cluster: 0x0000 attr: 0x4000 of node 0x90FD9FFFFE6E675E (seems to be active)
13:06:55:753 Bind response success for 0x90fd9ffffe6e675e ep: 0x01 cluster: 0x0008
13:06:55:754 skip configure report for cluster: 0x0008 attr: 0x0000 of node 0x90FD9FFFFE6E675E (wait reading or unsupported)
13:06:55:956 don't close database yet, keep open for 900 seconds
13:06:58:544 ZCL attribute report 0x90FD9FFFFE6E675E for cluster: 0x0000, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
13:07:00:868 ZCL attribute report 0x00158D0004626CBA for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
13:07:03:106 don't close database yet, keep open for 900 seconds
13:07:08:958 don't close database yet, keep open for 900 seconds
13:07:10:610 verified group capacity: 255 and group count: 1 of LightNode 0x000b57fffed4d3d7
13:07:10:610 0x000b57fffed4d3d7 found group 0xFFF0
13:07:15:030 don't close database yet, keep open for 900 seconds
13:07:22:807 don't close database yet, keep open for 900 seconds
13:07:23:029 Current channel 25
13:07:23:036 Device TTL 1052 s flags: 0x7
13:07:30:139 don't close database yet, keep open for 900 seconds
13:07:36:384 verified group capacity: 255 and group count: 1 of LightNode 0x000b57fffe34a388
13:07:36:384 0x000b57fffe34a388 found group 0xFFF0
13:07:38:044 don't close database yet, keep open for 900 seconds
13:07:39:094 	0xD0CF5EFFFEEF2AF3 force poll (2)
13:07:39:112 	0x000B57FFFED5B120 force poll (2)
13:07:39:118 ZCL attribute report 0xD0CF5EFFFEEF2AF3 for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
13:07:39:197 	0xD0CF5EFFFEE9F91A force poll (2)
13:07:39:242 ZCL attribute report 0xD0CF5EFFFEE9F91A for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
13:07:40:301 	0x000B57FFFED4D3D7 force poll (2)
13:07:40:319 ZCL attribute report 0x000B57FFFED4D3D7 for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
13:07:40:634 ZCL attribute report 0x000B57FFFED5B120 for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
13:07:43:775 no button map for: lumi.relay.c2acn01 ep: 0x01 cl: 0x000A cmd: 0x00 pl[0]: 000
13:07:44:051 don't close database yet, keep open for 900 seconds
13:07:49:011 remove outdated neighbor 0xC532
13:07:49:029 don't close database yet, keep open for 900 seconds
13:08:20:866 don't close database yet, keep open for 900 seconds
13:08:20:871 Remove websocket 172.30.32.1:38616 after error Unknown error
13:08:20:879 ZCL attribute report 0x00158D0004626CBA for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
13:08:22:553 no button map for: lumi.weather ep: 0x01 cl: 0x0000 cmd: 0x0A pl[0]: 001
13:08:22:553 ZCL attribute report 0x00158D000411B4AB for cluster: 0x0000, ep: 0x01, frame control: 0x18, mfcode: 0x0000 
13:08:22:553 0x00158D000411B4AB extract Xiaomi special attribute 0xFF01
13:08:22:553 	01 battery 3025 (0x0BD1)
13:08:22:553 	04 unknown 17320 (0x43A8)
13:08:22:553 	05 RSSI dB (?) 44 (0x002C)
13:08:22:553 	06 LQI (?) 4294967296 (0x0100000000)
13:08:22:553 	64 temperature 2250
13:08:22:553 	65 humidity 5842
13:08:22:553 	66 pressure 101287 (1013)
13:08:22:553 	0a unknown 36388 (0x8E24)
13:08:23:039 Current channel 25
13:08:23:047 Device TTL 992 s flags: 0x7
13:08:24:013 binding for cluster 0x0000 of 0xD0CF5EFFFEEF2AF3 exists (verified by reporting)
13:08:24:013 binding for cluster 0x0006 of 0xD0CF5EFFFEEF2AF3 exists (verified by reporting)
13:08:24:013 binding for cluster 0x0008 of 0xD0CF5EFFFEEF2AF3 exists (verified by reporting)
13:08:24:194 ZCL configure reporting rsp seq: 194 0xD0CF5EFFFEEF2AF3 for ep: 0x01 cluster: 0x0006 attr: 0x0000 status: 0x00
13:08:24:202 ZCL configure reporting rsp seq: 195 0xD0CF5EFFFEEF2AF3 for ep: 0x01 cluster: 0x0008 attr: 0x0000 status: 0x00
13:09:27:077 don't close database yet, keep open for 900 seconds
13:09:27:082 remove outdated neighbor 0x5AF6
13:09:27:083 New websocket 172.30.32.1:45732 (state: 3) 
13:09:27:117 Current channel 25
13:09:27:125 Device TTL 928 s flags: 0x7
13:09:27:137 no button map for: lumi.relay.c2acn01 ep: 0x01 cl: 0x000A cmd: 0x00 pl[0]: 000
13:09:27:548 	0x000D6FFFFEC2E2B4 force poll (2)
13:10:00:332 don't close database yet, keep open for 900 seconds
13:10:00:342 Remove websocket 172.30.32.1:45732 after error Unknown error
13:10:00:343 remove outdated neighbor 0x1681
13:10:00:383 dev /dev/ttyAMA0
13:10:00:387 no button map for: lumi.relay.c2acn01 ep: 0x01 cl: 0x000A cmd: 0x00 pl[0]: 000
13:10:00:387 GW firmware version: 0x26580700
13:10:00:387 GW firmware version is up to date: 0x26580700
13:10:00:888 ZCL attribute report 0x00158D0004626CBA for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
13:10:40:915 don't close database yet, keep open for 900 seconds
13:10:40:919 New websocket 172.30.32.1:45872 (state: 3) 
13:10:40:929 ZCL attribute report 0x00124B001D440155 for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
13:10:40:945 Current channel 25
13:10:40:953 Device TTL 854 s flags: 0x7
13:10:40:965 ZCL attribute report 0x00124B001D440E65 for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
13:10:40:968 ZCL attribute report 0x00124B001D441869 for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
13:10:42:166 0x00124B001D441869 error APSDE-DATA.confirm: 0xE9 on task
13:10:42:396 	0x000D6FFFFEC2E2B4 force poll (2)
13:10:43:947 no button map for: lumi.relay.c2acn01 ep: 0x01 cl: 0x000A cmd: 0x00 pl[0]: 000
13:11:47:956 don't close database yet, keep open for 900 seconds
13:11:47:989 Remove websocket 172.30.32.1:45872 after error Unknown error
13:11:48:083 New websocket 172.30.32.1:45978 (state: 3) 
13:11:48:084 ZCL attribute report 0x00158D0004626CBA for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
13:11:48:101 Current channel 25
13:11:48:108 Device TTL 787 s flags: 0x7
13:11:48:603 	0x000D6FFFFEC2E2B4 force poll (2)
13:11:53:012 remove outdated neighbor 0x1681
13:11:55:725 don't close database yet, keep open for 900 seconds
13:12:00:906 ZCL attribute report 0x00158D0004626CBA for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
13:12:01:032 don't close database yet, keep open for 900 seconds
13:12:03:011 remove outdated neighbor 0xC788
13:12:05:266 ZCL attribute report 0x90FD9FFFFE2AC557 for cluster: 0x0000, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
13:12:05:545 ZCL attribute report 0x90FD9FFFFE29AFA0 for cluster: 0x0000, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
13:12:07:034 don't close database yet, keep open for 900 seconds
13:12:08:011 remove outdated neighbor 0xDCD7
13:12:08:029 ZCL attribute report 0x000B57FFFED593FB for cluster: 0x0000, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
13:12:09:512 binding for cluster 0x0000 of 0x000B57FFFED4D3D7 exists (verified by reporting)
13:12:09:512 skip configure report for cluster: 0x0000 attr: 0x4000 of node 0x000B57FFFED4D3D7 (seems to be active)
13:12:09:512 binding for cluster 0x0006 of 0x000B57FFFED4D3D7 exists (verified by reporting)
13:12:09:513 binding for cluster 0x0008 of 0x000B57FFFED4D3D7 exists (verified by reporting)
13:12:09:585 ZCL attribute report 0x000B57FFFE8A375A for cluster: 0x0000, ep: 0x01, frame control: 0x08, mfcode: 0x0000

**Comment by PaulAntonDeen** [comment]
No difference to the system log after changing back to the full hardware id, still get the freeze-ups

**Comment by Mimiix** [comment]
13:10:42:166 0x00124B001D441869 error APSDE-DATA.confirm: 0xE9 on task

I have no clue which devidce that is (Incomplete log from HAdebug logs but the VNC should show). However, that indicates :
```Is issued when the coordinator sends out a command but no acknowledgement (ACK) was returned from the target receivers next hop (1-hop only).``` see: https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Zigbee-Error-Codes-in-the-Log#0xe9-no-mac-ack-received

However, this log still says your not using the serial 13:10:00:383 dev /dev/ttyAMA0

In your next post, can you include:
- A screenshot of your network (Use VNC to connect, Addon page describes how)
- Make another log like the last one you posted, but with the serial like this:` /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_XXXXXXXX-if00"`

**Comment by vegetate7** [comment]
I think this issue is related somehow to IO load. I have same. The addon have quite small timeouts, but messages from decons libs are delayed because of IO. Small evidence of this is the deconz-gui (VNC app) freezing same time as addon disconnects.
Resolved changing SD-Card and by tuning Recorder and History components to minimize SD-Card IO.

**Comment by PaulAntonDeen** [comment]
![image](https://user-images.githubusercontent.com/25848961/87543647-62571880-c6a5-11ea-91fa-955564e9a73d.png)

**Comment by PaulAntonDeen** [comment]
![Screen Sharing Picture July 15, 2020 at 14 30 10 GMT+2](https://user-images.githubusercontent.com/25848961/87545179-dabed900-c6a7-11ea-8a09-7507472dc670.png)

Waiting for another hang-up to occur.

**Comment by PaulAntonDeen** [comment]
> I think this issue is related somehow to IO load. I have same. The addon have quite small timeouts, but messages from decons libs are delayed because of IO. Small evidence of this is the deconz-gui (VNC app) freezing same time as addon disconnects.
> Resolved changing SD-Card and by tuning Recorder and History components to minimize SD-Card IO.

Yes all of HA started freezing when I initially started using my DSMR component. So i have most things excluded from the recorder and my db is pretty small with low IO.

**Comment by PaulAntonDeen** [comment]
2020-07-15 14:49:48 DEBUG (MainThread) [pydeconz.websocket] Websocket starting
2020-07-15 14:49:48 DEBUG (MainThread) [pydeconz.websocket] Reconnecting to deCONZ in 15.
2020-07-15 14:49:49 INFO (MainThread) [homeassistant.components.automation] Executing Achterkamer kastlicht
2020-07-15 14:49:49 INFO (MainThread) [homeassistant.components.automation] Achterkamer kastlicht: Running script
2020-07-15 14:49:49 INFO (MainThread) [homeassistant.components.automation] Achterkamer kastlicht: Executing step call service
2020-07-15 14:50:00 INFO (MainThread) [homeassistant.components.automation] Executing Achterkamerspots naar 1000lm
2020-07-15 14:50:00 INFO (MainThread) [homeassistant.components.automation] Achterkamerspots naar 1000lm: Running script
2020-07-15 14:50:00 INFO (MainThread) [homeassistant.components.automation] Achterkamerspots naar 1000lm: Executing step call service
2020-07-15 14:50:00 INFO (MainThread) [homeassistant.components.automation] Executing Voorkamerspots naar eettafel
2020-07-15 14:50:00 INFO (MainThread) [homeassistant.components.automation] Voorkamerspots naar eettafel: Running script
2020-07-15 14:50:00 INFO (MainThread) [homeassistant.components.automation] Voorkamerspots naar eettafel: Executing step call service
2020-07-15 14:50:00 INFO (MainThread) [homeassistant.components.automation] Executing Voorkamerspots naar Augurk
2020-07-15 14:50:00 INFO (MainThread) [homeassistant.components.automation] Voorkamerspots naar Augurk: Running script
2020-07-15 14:50:00 INFO (MainThread) [homeassistant.components.automation] Voorkamerspots naar Augurk: Executing step call service
2020-07-15 14:50:00 WARNING (MainThread) [homeassistant.helpers.entity] Update of media_player.huiskamer_tv is taking over 10 seconds
2020-07-15 14:50:00 WARNING (MainThread) [homeassistant.components.media_player] Updating webostv media_player took longer than the scheduled update interval 0:00:10
2020-07-15 14:50:03 DEBUG (MainThread) [pydeconz.websocket] Websocket starting
2020-07-15 14:53:00 DEBUG (MainThread) [pydeconz.websocket] Websocket running
2020-07-15 14:53:01 INFO (MainThread) [homeassistant.components.automation] Executing Achterkamer kastlicht
2020-07-15 14:53:01 INFO (MainThread) [homeassistant.components.automation] Achterkamer kastlicht: Running script
2020-07-15 14:53:01 INFO (MainThread) [homeassistant.components.automation] Achterkamer kastlicht: Executing step call service
2020-07-15 14:53:01 INFO (MainThread) [homeassistant.components.automation] Executing Achterkamerspots naar 1000lm
2020-07-15 14:53:01 INFO (MainThread) [homeassistant.components.automation] Achterkamerspots naar 1000lm: Running script
2020-07-15 14:53:01 INFO (MainThread) [homeassistant.components.automation] Achterkamerspots naar 1000lm: Executing step call service
2020-07-15 14:53:01 INFO (MainThread) [homeassistant.components.automation] Executing Voorkamerspots naar eettafel
2020-07-15 14:53:01 INFO (MainThread) [homeassistant.components.automation] Voorkamerspots naar eettafel: Running script
2020-07-15 14:53:01 INFO (MainThread) [homeassistant.components.automation] Voorkamerspots naar eettafel: Executing step call service
2020-07-15 14:53:01 INFO (MainThread) [homeassistant.components.automation] Executing Voorkamerspots naar Augurk
2020-07-15 14:53:01 INFO (MainThread) [homeassistant.components.automation] Voorkamerspots naar Augurk: Running script
2020-07-15 14:53:01 INFO (MainThread) [homeassistant.components.automation] Voorkamerspots naar Augurk: Executing step call service
2020-07-15 14:53:01 DEBUG (MainThread) [pydeconz.websocket] {"attr":{"lastannounced":null,"lastseen":"2020-07-15T12:53:00Z","manufacturername":"IKEA of Sweden","modelid":"TRADFRI control outlet","name":"Ventilator","swversion":"2.0.022","type":"On/Off plug-in unit","uniqueid":"00:0d:6f:ff:fe:c2:e4:20-01"},"e":"changed","id":"21","r":"lights","t":"event","uniqueid":"00:0d:6f:ff:fe:c2:e4:20-01"}
2020-07-15 14:53:01 DEBUG (MainThread) [pydeconz.websocket] {"attr":{"lastannounced":null,"lastseen":"2020-07-15T12:53:01Z","manufacturername":"IKEA of Sweden","modelid":"TRADFRI bulb GU10 W 400lm","name":"Douche achter","swversion":"1.2.214","type":"Dimmable light","uniqueid":"90:fd:9f:ff:fe:6f:89:7f-01"},"e":"changed","id":"15","r":"lights","t":"event","uniqueid":"90:fd:9f:ff:fe:6f:89:7f-01"}
2020-07-15 14:53:01 DEBUG (MainThread) [pydeconz.gateway] Sending "put" "{'on': False}" to "172.30.33.2 /lights/40/state"
2020-07-15 14:53:01 DEBUG (MainThread) [pydeconz.gateway] HTTP request response: [{'success': {'/lights/40/state/on': False}}]
2020-07-15 14:53:01 DEBUG (MainThread) [pydeconz.websocket] {"attr":{"lastannounced":null,"lastseen":"2020-07-15T12:53:01Z","manufacturername":"FeiBit","modelid":"FNB56-ZSC01LX1.2","name":"Eettafel","swversion":"00000001","type":"Dimmable light","uniqueid":"00:15:8d:00:04:62:6c:ba-01"},"e":"changed","id":"54","r":"lights","t":"event","uniqueid":"00:15:8d:00:04:62:6c:ba-01"}
2020-07-15 14:53:02 DEBUG (MainThread) [pydeconz.websocket] {"attr":{"lastannounced":null,"lastseen":"2020-07-15T12:53:02Z","manufacturername":"IKEA of Sweden","modelid":"TRADFRI bulb E27 opal 1000lm","name":"1000 lm","swversion":"1.2.214","type":"Dimmable light","uniqueid":"00:0b:57:ff:fe:34:a3:88-01"},"e":"changed","id":"6","r":"lights","t":"event","uniqueid":"00:0b:57:ff:fe:34:a3:88-01"}
2020-07-15 14:53:02 DEBUG (MainThread) [pydeconz.websocket] {"attr":{"lastannounced":null,"lastseen":"2020-07-15T12:53:02Z","manufacturername":"eWeLink","modelid":"SA-003-Zigbee","name":"Garage buiten","swversion":null,"type":"On/Off plug-in unit","uniqueid":"00:12:4b:00:1c:d5:fc:9c-01"},"e":"changed","id":"63","r":"lights","t":"event","uniqueid":"00:12:4b:00:1c:d5:fc:9c-01"}
2020-07-15 14:53:03 DEBUG (MainThread) [pydeconz.websocket] {"e":"changed","id":"43","r":"sensors","state":{"current":0,"lastupdated":"2020-07-15T12:53:03.781","power":-1,"voltage":231},"t":"event","uniqueid":"00:15:8d:00:04:28:ec:46-01-0b04"}
2020-07-15 14:53:05 DEBUG (MainThread) [pydeconz.websocket] {"attr":{"lastannounced":null,"lastseen":"2020-07-15T12:53:05Z","manufacturername":"eWeLink","modelid":"SA-003-Zigbee","name":"Garage deur opener","swversion":null,"type":"Unknown","uniqueid":"00:12:4b:00:1d:44:01:55-01"},"e":"changed","id":"5","r":"lights","t":"event","uniqueid":"00:12:4b:00:1d:44:01:55-01"}

**Comment by Mimiix** [comment]
I meant this log: https://github.com/home-assistant/hassio-addons/issues/1463#issuecomment-658708220

In relation to @vegetate7 says, does it change when you turn the DSMR off (and other IO intensive stuff?). It might be the websocket just timing out.

What type of SD card are you using? Could it be in that?

I still am not sure which device belongs to the 0x00124B001D441869 mac-address.

Are you on discord perhaps? Might be easier in communication.

**Comment by CASATAJO** [comment]
seems similar to: https://github.com/home-assistant/core/issues/37372
I rolled back to 3.5.2 and my problem went away (a backup from May 13), 6.1.1 stioll shows the problem

**Comment by Robin-St** [comment]
I experienced similar problems and noticed some correlation between CPU load and the frequency of the errors occurring. Thou the did not disappear even when running just home-assistant and the deconz add-on on the RPi, turning off all other things. Even tested with the network disconnected to see if it would change anything.

What in the end solved/mitigated the problem for me was  to replace the SD-card to one with a A1 with better support for random writes. So there seems to be something in the integration that is on the edge timing wise that causes this interruptions.

**Comment by PaulAntonDeen** [comment]
still broken

**Comment by MarkusHornbach** [comment]
Does anyone still have this disconnects after updating firmware to the latest version?
I changed my sd card to an A2 labeled one and updated firmware nearly at the same time, some days ago. No disconnects since that day, but it's hard to find out the reason.

**Comment by PaulAntonDeen** [comment]
Yes, still have the issue, tested it this weekend.

**Comment by Wafwafe** [comment]
Same here.

**Comment by austwhite** [comment]
I have not had this issue in the last 3 to 4 months.    The only issue I have with deCONZ now is that the Conbee II stick is a bit crap.  The slightest external interference and the whole ZigBee network crashes.

**Comment by PaulAntonDeen** [comment]
I have moved away to deconz in a standalone docker and have not tested this for a long time. I left it open as a gathering for other users but since it is not being picked up i'm closing the issue.
