### ISSUE TITLE
IPv6 Config URL causing duckdns script to exit with status 7

### ISSUE THREAD

**Issue by mattclar** [home-assistant/addons#1715]
## The problem
DuckDNS addon is failing and exiting the script when a URL value is added for ipv6 only.
I have tested with just adding a static IPv6 address as the config value and this works fine
Also only adding a URL for the ipv4 value works
It seems to be only when I use a URL value for the ipv6 config that it fails?!

## Environment

- Add-on with the issue: DuckDNS
- Add-on release with the issue: 1.12.4
- Last working add-on release (if known): NA
- Operating environment (OS/Supervised): Hassos 5.8

## Problem-relevant configuration

```lets_encrypt:
  accept_terms: true
  certfile: fullchain.pem
  keyfile: privkey.pem
token: 6697a35c-7b8f-48de-8c4e-##########
domains:
  - arthurst.duckdns.org
aliases: []
seconds: 300
ipv6: 'https://api6.ipify.org/'

```

## Traceback/Error logs

```[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
# INFO: Using main config file /data/workdir/config
+ Account already registered!
[cmd] /run.sh exited 7
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

```

**Comment by make-all** [comment]
I hadn't figured out the reason, but I have been seeing this error from duckdns since the last update at the beginning of November.
My configuration is the same: 
    ipv6: 'https://api6.ipify.org/'
and nothing for ipv4.

My ISP allocates IPv6 prefixes dynamically, and the IPv4 addresses are CG-NAT, so no route back in from the internet.  The DuckDNS plugin has never really worked correctly for this setup, but at least it used to keep running for the letsencrypt cert renewal.

**Comment by nicogramm** [comment]
Same problem here.
I use the Nginx Proxy Manager for my certificate so I have Let's Encrypt disabled in this Add-on (`lets_encrypt.accept_terms`=`false`).
But still, when I set the config option for IPv6 the Add-on exists with status 7.

## Add-on log output
```text
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cmd] /run.sh exited 7
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by nicogramm** [comment]
I built a workaround for setting the IPv6 address in DuckDNS.

It uses two [DNS IP Sensor](https://www.home-assistant.io/integrations/dnsip/)s and a [RESTful Command](https://www.home-assistant.io/integrations/rest_command/#how-to-test-your-new-rest-command) to regularly fetch the current public IP addresses and send them to DuckDNS.
For this you need to create a new automation, which then regularly starts the REST command.

## Example configuration
```yaml
sensor:
  - platform: dnsip
    name: myipv4
    ipv6: false
  - platform: dnsip
    name: myipv6
    ipv6: true

rest_command:
  update_ips:
    url: "https://www.duckdns.org/update?domains=<DOMAIN>&token=<TOKEN>&ip={{ states('sensor.myipv4') }}&ipv6={{ states('sensor.myipv6') }}"
```

## See also
https://www.duckdns.org/spec.jsp

**Comment by vitorma** [comment]
same problem here

I'm using this script as a workaround: https://github.com/gtwy/IPv6forDuckDNS

**Comment by ymarkus** [comment]
Some more information: if I input a `https://api.ipify.org/`, so a ipv4 gets passed, or if I input an ipv6, it does work (the IPv4 gets a "KO" response from duckdns of course). So my guess is that the error comes from exactly this line:
```bash
[[ ${IPV6} != *:/* ]] && ipv6=${IPV6} || ipv6=$(curl -s -m 10 "${IPV6}")
```
My guess: we need more quotes:
```bash
[[ ${IPV6} != *:/* ]] && ipv6=${IPV6} || ipv6="$(curl -s -m 10 "${IPV6}")"
```

I think this is an bashio issue though, as the script works perfectly as a bash script...

**Comment by ymarkus** [comment]
Deleted my last comment, as I have found the issue: The container that the addon runs in doesn't have an ipv6 address and therefore can not reach ipv6 APIs. 
I've submitted a PR request that fixes this.

**Comment by make-all** [comment]
The issue still occurs on 1.12.5 version of add-on.

**Comment by make-all** [comment]
Proposed fixes are mentioned above, but have not been installed. So the issue still persists.

**Comment by make-all** [comment]
I found a workaround that makes the addon work for both IPv6 only address setting, and for certificate update.  The other workarounds are bypassing the addon to find other methods of setting an IPv6 address, but this leaves the certificates still not updating.

For IPv6 URL, set http://homeassistant:8123/local/ipv6.txt

Save the following script as /etc/periodic/15min/update-ipv6 and `chmod +x update-ipv6`

```bash
#!/usr/bin/env bashio
bashio::network.ipv6_address wlan0 | grep ^24 | sed 's_/64__' > /config/www/ipv6.txt
```

This works around the fact that the container the add-on is running in does not have IPv6 access, so cannot use external  web services that return the IPv6 used to access them.

**Comment by make-all** [comment]
The above workaround seems to be defeated by the fact that the /etc/periodic/ directory is cleared on OS upgrade.

**Comment by make-all** [comment]
Not stale

**Comment by EinsEins11** [comment]
not stale

**Comment by MeirSD** [comment]
> The above workaround seems to be defeated by the fact that the /etc/periodic/ directory is cleared on OS upgrade.

Putting the following in the crontab instead of using the periodic directory worked to restore your workaround:
*/5 * * * * ip addr | grep -oP '2600.*(?=/128)' > /usr/share/hassio/homeassistant/www/ipv6.txt

Some things to note for new people trying this:
- You still need to change the 2600 and 128 to match your ipv6 subnet
- You need to have an ssl proxy set up (NGINX Home Assistant SSL proxy)
- /usr/share/hassio/homeassistant/ should be changed to the directory where your configuration.yaml lives
- If you've never used the www directory you have to create that folder and reboot HA

**Comment by make-all** [comment]
Thanks, I had to make some tweeks to the grep part, because the version installed in HassOS does not seem to support the -P option, so I changed it to `grep -o '2600[^/]*' instead.

**Comment by make-all** [comment]
not stale

And it looks like the workaround of putting it in .crontab instead of /etc is also wiped by an OS upgrade.

**Comment by martymarty004** [comment]
I found this [custom component](https://github.com/lfhohmann/ha-duckdns_ipv4_ipv6) that does the job, but it would be better if this Addon worked as it should, without the need of another component.

**Comment by inverse** [comment]
Still an issue.

**Comment by culverscruple** [comment]
still an issue

**Comment by barn** [comment]
So I think it's because the container in question doesn't have v6 in it.

```bash
[23:34:48] INFO: HELLO
[23:34:48] INFO: doing a loop
++ [[ '' != *:/* ]]
++ ipv4=
++ [[ https://api6.ipify.org/ != *:/* ]]
++ ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
85: eth0@if86: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 02:42:ac:1e:21:15 brd ff:ff:ff:ff:ff:ff
    inet 172.30.33.5/23 brd 172.30.33.255 scope global eth0
       valid_lft forever preferred_lft forever
++ ip -6 addr show
++ echo boop
boop
++ ip route
default via 172.30.32.1 dev eth0 
172.30.32.0/23 dev eth0 scope link  src 172.30.33.5 
++ ip -6 route
+++ curl --verbose -s -m 10 https://api6.ipify.org/
*   Trying 2607:f2d8:4010:8::2:443...
* Immediate connect fail for 2607:f2d8:4010:8::2: Address not available
*   Trying 2607:f2d8:4010:c::2:443...
* Immediate connect fail for 2607:f2d8:4010:c::2: Address not available
*   Trying 2607:f2d8:4010:b::2:443...
* Immediate connect fail for 2607:f2d8:4010:b::2: Address not available
* Closing connection 0
++ ipv6=
[cmd] /run.sh exited 7
```

from hacking up a test version. From doing the same with `ip -6 addr show` and `ip -6 route` it doesn't have any v6. Which is why it can't even get them locally. The container just isn't being run with a v6 interface at all.

There's the `host_network: true` parameter in https://developers.home-assistant.io/docs/add-ons/configuration/#optional-configuration-options but that still doesn't seem to give v6 address. So I presume the dockerd isn't run with v6 support? but I haven't gone in and looked on the supervisor.

Some cronned version as people are using above to get the IP is sadly probably the best way. This is perhaps a safer command for getting a v6 IP out, as it will cope better if there's more than one match.

```bash
test% ]% ip -6 address show dev "$(ip -6 route show default | awk '{print $5;exit}')" scope global | awk '/inet6 [^f]/ {print $2;exit}' | cut -f 1 -d '/'
```

(work out the v6 default route, print the first interface. Use that for a v6 show addresses command, only global ones too. Find the first non 'f' starting address (so it should be a globally routed one), print the first one, and remove the prefix length)

**Comment by mjunold** [comment]
still an issue

**Comment by sbeagle25** [comment]
My configuration is the same:
ipv6: 'https://api6.ipify.org/'
and nothing for ipv4.
when I try to use ipv6 only, the log shows as below and stop running
`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
# INFO: Using main config file /data/workdir/config
+ Account already registered!
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

**Comment by martymarty004** [comment]
> I found this [custom component](https://github.com/lfhohmann/ha-duckdns_ipv4_ipv6) that does the job, but it would be better if this Addon worked as it should, without the need of another component.

I've never had any issues since I started using this custom component, even though I'd still like to see this problem fixed in the official addon.

**Comment by make-all** [comment]
I see there was an update this week that added the ability to get the IPv6 address from the supervisor.  I am no longer on CG-NAT, so using IPv4 now, but it might be worth trying that insread of the URL if you are still affected by this issue.

**Comment by martymarty004** [comment]
Since I already had everything up-to-date I didn't mind trying to re-configure the addon, and it is actually working right now.

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
# INFO: Using main config file /data/workdir/config
+ Account already registered!
[18:30:25] INFO: OK
2a##:####:####:0:####:####:####:88f
NOCHANGE
[18:30:25] INFO: OK
1##.###.###.##7
NOCHANGE
[18:30:26] INFO: Renew certificate for domains: #############.duckdns.org and aliases: 
# INFO: Using main config file /data/workdir/config
Processing #############.duckdns.org
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Jul 28 22:00:12 2022 GMT (Longer than 30 days). Skipping renew!
```

**Comment by sbeagle25** [comment]
I use mobile network share in my house so I got only one public ipv6 address. I have to use the url to get public ipv6 address but it still not working even I have everything updated.

**Comment by culverscruple** [comment]
> Since I already had everything up-to-date I didn't mind trying to re-configure the addon, and it is actually working right now.
> 
> (I simply added the "default" IPv6 interface to the addon config)
> 
> ```
> s6-rc: info: service s6rc-oneshot-runner: starting
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service fix-attrs successfully started
> s6-rc: info: service legacy-cont-init: starting
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service legacy-services: starting
> s6-rc: info: service legacy-services successfully started
> # INFO: Using main config file /data/workdir/config
> + Account already registered!
> [18:30:25] INFO: OK
> 2a##:####:####:0:####:####:####:88f
> NOCHANGE
> [18:30:25] INFO: OK
> 1##.###.###.##7
> NOCHANGE
> [18:30:26] INFO: Renew certificate for domains: #############.duckdns.org and aliases: 
> # INFO: Using main config file /data/workdir/config
> Processing #############.duckdns.org
>  + Checking domain name(s) of existing cert... unchanged.
>  + Checking expire date of existing cert...
>  + Valid till Jul 28 22:00:12 2022 GMT (Longer than 30 days). Skipping renew!
> ```

So I can confirm that this also seems to solve the issue for me. To be clear, all I did was replace
`ipv6: 'https://api6.ipify.org/'`
with
`ipv6: default`
in the config

**Comment by mdegat01** [comment]
@mattclar does the solution shown above work for you as well? Can this issue be closed?

**Comment by sbeagle25** [comment]
It still unavailable when using a url in ipv6. If I set as default it gets a internal ipv6 cause I using CG-NAT in my house.

**Comment by sbeagle25** [comment]
@mdegat01 Maybe I misunderstand the CG-NAT. I can get a public ipv6 address but just

**Comment by mattclar** [comment]
@mdegat01 yes problem solved!! 😊

**Comment by mdegat01** [comment]
@sbeagle25 ok perhaps I am confused. So to confirm your ISP gives you a public ipv6 address that is just for your house. It's not an internal one but somehow `default` is getting something different? Also please share your system info from [settings -> system -> system health]( https://my.home-assistant.io/redirect/system_health/)

**Comment by sbeagle25** [comment]
@mdegat01 I use a telephone sim card to share the interent for my house by an AP which support the sim card. So I can only get one public ipv6 on the AP. If I use the default in Duckdns, it will get the internal ipv6 address which came from the AP.

> System Health
> 
> version: core-2022.6.1
> installation_type: Home Assistant OS
> dev: false
> hassio: true
> docker: true
> user: root
> virtualenv: false
> python_version: 3.9.12
> os_name: Linux
> os_version: 5.15.32-v8
> arch: aarch64
> timezone: Asia/Taipei
> 
> 
> GitHub API: ok
> GitHub Content: ok
> GitHub Web: ok
> GitHub API Calls Remaining: 4989
> Installed Version: 1.24.5
> Stage: running
> Available Repositories: 1134
> Downloaded Repositories: 24
> 
> 
> logged_in: false
> can_reach_cert_server: ok
> can_reach_cloud_auth: ok
> can_reach_cloud: ok
> 
> 
> host_os: Home Assistant OS 8.1
> update_channel: stable
> supervisor_version: supervisor-2022.05.3
> agent_version: 1.2.1
> docker_version: 20.10.14
> disk_total: 29.0 GB
> disk_used: 21.6 GB
> healthy: true
> supported: true
> board: rpi4-64
> supervisor_api: ok
> version_api: ok
> installed_addons: AirCast (3.4.0), Dnsmasq (1.4.4), ESPHome (2022.3.1), FTP (4.6.0), File editor (5.3.3), Glances (0.16.0), Home Assistant Google Drive Backup (0.105.2), MariaDB (2.4.0), Mosquitto broker (6.1.2), SSH & Web Terminal (10.1.3), Samba share (10.0.0), Spotify Connect (0.12.1), Studio Code Server (5.1.2), Terminal & SSH (9.4.0), ZeroTier One (0.15.0), Zigbee2mqtt (1.18.1-1), motionEye (0.18.0), Duck DNS (1.15.0)
> 
> 
> dashboards: 2
> resources: 12
> views: 8
> mode: storage
> 
> 
> oldest_recorder_run: 2022年6月15日 01:14
> current_recorder_run: 2022年6月15日 09:14
> estimated_db_size: 2.81 MiB
> database_engine: mysql
> database_version: 10.4.19
> 
> 
> api_endpoint_reachable: ok

**Comment by mdegat01** [comment]
@sbeagle25 ok since it seems like your issue is a bit different then the original authors (who as was able to leverage the `default` option) can you open a new issue? Sounds like your setup should be working so still an issue but want to track it separately
