### ISSUE TITLE
Strange log messages in Samba Add-on 9.5.0

### ISSUE THREAD

**Issue by martymarty004** [home-assistant/addons#2040]
## The problem

Today I updated the add-on to the latest version and I noticed some strange messages at the start of the Samba Share Add-on logs. 
I don't know if they are normal log messages, but I'm reporting the issue just to be sure.
I don't know whether this messages from the logs were already present in previous versions, I noticed them only after the update.
The add-on still works just fine.

## Environment

- Add-on with the issue: Samba share
- Add-on release with the issue: 9.5.0
- Last working add-on release (if known): N/A
- Operating environment (OS/Supervised): Home Assistant OS

## Problem-relevant configuration

```yaml
workgroup: WORKGROUP
username: '!secret Samba_User'
password: '!secret Samba_Passw'
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 'fe80::/10'
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: false
```

## Traceback/Error logs

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] samba.sh: executing... 
parse error: Expected string key before ':' at line 1, column 4
[16:17:56] ERROR: Unknown HTTP error occured
[16:17:56] INFO: Using hostname=homeassistant interface=
No builtin backend found, trying to load plugin
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
account_policy_get: tdb_fetch_uint32_t failed for type 1 (min password length), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 2 (password history), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 3 (user must logon to change password), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 4 (maximum password age), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 5 (minimum password age), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 6 (lockout duration), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 7 (reset count minutes), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 8 (bad lockout attempt), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 9 (disconnect time), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 10 (refuse machine password change), returning 0
Added user homeassistant.
[cont-init.d] samba.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
nmbd version 4.13.8 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
Registered MSG_REQ_POOL_USAGE
added interface docker0 ip=172.17.0.1 bcast=172.17.255.255 netmask=255.255.0.0
added interface hassio ip=172.30.32.1 bcast=172.30.33.255 netmask=255.255.254.0
added interface eth0 ip=192.168.1.77 bcast=192.168.1.255 netmask=255.255.255.0
making subnet name:192.168.1.77 Broadcast address:192.168.1.255 Subnet mask:255.255.255.0
making subnet name:172.30.32.1 Broadcast address:172.30.33.255 Subnet mask:255.255.254.0
making subnet name:172.17.0.1 Broadcast address:172.17.255.255 Subnet mask:255.255.0.0
making subnet name:UNICAST_SUBNET Broadcast address:0.0.0.0 Subnet mask:0.0.0.0
making subnet name:REMOTE_BROADCAST_SUBNET Broadcast address:0.0.0.0 Subnet mask:0.0.0.0
daemon_ready: daemon 'nmbd' finished starting up and ready to serve connections
smbd version 4.13.8 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
Processing section "[config]"
Processing section "[addons]"
Processing section "[ssl]"
Processing section "[share]"
Processing section "[backup]"
Processing section "[media]"
added interface docker0 ip=172.17.0.1 bcast=172.17.255.255 netmask=255.255.0.0
added interface hassio ip=172.30.32.1 bcast=172.30.33.255 netmask=255.255.254.0
added interface eth0 ip=192.168.1.77 bcast=192.168.1.255 netmask=255.255.255.0
INFO: Profiling support unavailable in this build.
Registered MSG_REQ_POOL_USAGE
No builtin backend found, trying to load plugin
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_POOL_USAGE
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
waiting for connections
check_for_master_browser_fail: Forcing election on workgroup WORKGROUP subnet 172.17.0.1
check_for_master_browser_fail: Forcing election on workgroup WORKGROUP subnet 172.30.32.1
check_for_master_browser_fail: Forcing election on workgroup WORKGROUP subnet 192.168.1.77
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.17.0.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.30.32.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 192.168.1.77
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.17.0.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.30.32.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 192.168.1.77
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.17.0.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.30.32.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 192.168.1.77
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.17.0.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.30.32.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 192.168.1.77
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.17.0.1
run_elections: >>> Won election for workgroup WORKGROUP on subnet 172.17.0.1 <<<
become_local_master_browser: Starting to become a master browser for workgroup WORKGROUP on subnet 172.17.0.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.30.32.1
run_elections: >>> Won election for workgroup WORKGROUP on subnet 172.30.32.1 <<<
become_local_master_browser: Starting to become a master browser for workgroup WORKGROUP on subnet 172.30.32.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 192.168.1.77
run_elections: >>> Won election for workgroup WORKGROUP on subnet 192.168.1.77 <<<
become_local_master_browser: Starting to become a master browser for workgroup WORKGROUP on subnet 192.168.1.77
*****
Samba name server HOMEASSISTANT is now a local master browser for workgroup WORKGROUP on subnet 172.17.0.1
*****
*****
Samba name server HOMEASSISTANT is now a local master browser for workgroup WORKGROUP on subnet 172.30.32.1
*****
*****
Samba name server HOMEASSISTANT is now a local master browser for workgroup WORKGROUP on subnet 192.168.1.77
*****
```

**Comment by marcelbrueckner** [comment]
I'm experiencing the same issue since I've updated the Samba add-on from 9.4.0 to v9.5.0.

There's also a corresponding Supervisor log entry
```bash
21-05-27 22:47:30 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on homeassistant/aarch64-addon-samba with version 9.5.0
21-05-27 22:47:31 ERROR (MainThread) [supervisor.api.security] Invalid token for access /network/interface/default/info
```

**Comment by atx32** [comment]
I am having the same problem. Note that the Samba log shows the network interface empty probably due to the invalid token error in the Supervisor log.

`[13:58:59] INFO: Using hostname=homeassistant interface=`

**Comment by mentalsoup** [comment]
> I am having the same problem. Note that the Samba log shows the network interface empty probably due to the invalid token error in the Supervisor log.
> 
> `[13:58:59] INFO: Using hostname=homeassistant interface=`

I have also encountered the above, noting that this does not seem to impact the ability to serve the directories however.

**Comment by jypsie** [comment]
exactly the same here.......

**Comment by kds69** [comment]
Hi,
Same logs but I cannot connect anymore from win10: user/password loggon dialog is not prompted anymore and instead samba is using NT authentification...which doesn't work.

Registered MSG_REQ_POOL_USAGE
check_ntlm_password:  Authentication for user [Sylvain] -> [xxx my windows user xxx] FAILED with error NT_STATUS_NO_SUCH_USER, authoritative=1
===============================================================
INTERNAL ERROR: Signal 11: Segmentation fault in pid 288 (4.13.8)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 288): Signal 11: Segmentation fault in 4.13.8
unable to produce a stack trace on this platform
coredump is handled by helper binary specified at /proc/sys/kernel/core_pattern

**Comment by jypsie** [comment]
I uninstalled and re-installed..... all ok now....

**Comment by martymarty004** [comment]
A re-installation of the Add-on didn't change anything for me, it was the first thing I tried.

The Add-on still works just fine, I just get these strange log messages at the start:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] samba.sh: executing... 
parse error: Expected string key before ':' at line 1, column 4
[22:39:51] ERROR: Unknown HTTP error occured
[22:39:51] INFO: Using hostname=homeassistant interface=
No builtin backend found, trying to load plugin
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
account_policy_get: tdb_fetch_uint32_t failed for type 1 (min password length), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 2 (password history), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 3 (user must logon to change password), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 4 (maximum password age), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 5 (minimum password age), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 6 (lockout duration), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 7 (reset count minutes), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 8 (bad lockout attempt), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 9 (disconnect time), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 10 (refuse machine password change), returning 0
Added user homeassistant.
[cont-init.d] samba.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

with the following error in the Supervisor:

```
ERROR (MainThread) [supervisor.api.middleware_security] Invalid token for access /network/interface/default/info
```

**Comment by twelve-cgn** [comment]
I'm experiencing the same issue. Re-install does not solve the problem.

parse error: Expected string key before ':' at line 1, column 4
