### ISSUE TITLE
[DuckDNS] No connection any more

### ISSUE THREAD

**Issue by franky1808** [home-assistant/addons#4121]
### Describe the issue you are experiencing

After a few issues after updating to 1.24 now there is no connection any more. Issues are not shown in the logs. 
There is no connection to DuckDNS any more without changing the config. 

`[21:32:10] INFO: Starting DuckDNS...
[21:32:11] INFO: Renew certificate for domains: *.mydomain.duckdns.org > futur3.duckdns.org and aliases: 
# INFO: Using main config file /data/workdir/config
Processing *.mydomain.duckdns.org
 + Checking domain name(s) of existing cert... changed!
 + Domain name(s) are not matching!
 + Names in old certificate: mydomain.duckdns.org
 + Configured names: *. mydomain.duckdns.org
 + Forcing renew.
 + Checking expire date of existing cert...
 + Valid till Nov 13 17:20:06 2025 GMT (Longer than 30 days). Ignoring because renew was forced!
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 1 authorizations URLs from the CA
 + Handling authorization for mydomain.duckdns.org
 + Found valid authorization for mydomain.duckdns.org
 + 0 pending challenge(s)
 + Requesting certificate...
Warning: Will read cert request from stdin since no -in option is given
 + Checking certificate...
 + Done!
 + Creating fullchain.pem...
 + Done!
[21:32:22] INFO: Final pass to combine individual certificates
# INFO: Using main config file /data/workdir/config
Processing *.mydomain.duckdns.org
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Nov 13 18:33:48 2025 GMT (Longer than 30 days). Skipping renew!`

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Duck DNS

### What is the version of the add-on?

1.25

### Steps to reproduce the issue

Configure my domain

`domains:
  - mydomain.duckdns.org
token: mytoken
aliases: []
lets_encrypt:
  accept_terms: true
  algo: secp384r1
  certfile: fullchain.pem
  keyfile: privkey.pem
seconds: 300
`

### System Health information

Aktuell stehen keine Reparaturen an

### Anything in the Supervisor logs that might be useful for us?

```txt
Host-Betriebssystem	Home Assistant OS 16.1
Update-Kanal	stable
Supervisor-Version	supervisor-2025.08.1
Agent-Version	1.7.2
Docker-Version	28.3.3
Gesamter Speicherplatz	56.6 GB
Belegter Speicherplatz	25.0 GB
Gesund	true
Unterstützt	true
host_connectivity	true
supervisor_connectivity	true
ntp_synchronized	true
virtualization	
Board	odroid-n2
Supervisor-API	ok
Versions-API	ok
Installierte Add-ons	Terminal & SSH (9.19.0), eufy-security-ws (1.9.3), RTSP Simple Server Add-on (v0.17.6), File editor (5.8.0), Advanced SSH & Web Terminal (21.0.2), Home Assistant Google Drive Backup (0.112.1), Mosquitto broker (6.5.1), Node-RED (20.0.0), Zigbee2MQTT (2.6.0-1), Duck DNS (1.25.0), NGINX Home Assistant SSL proxy (3.13.0), Studio Code Server (5.19.3), Ism7MQTT (v0.0.17), AMR2MQTT (2.1.2), Baby Buddy (2.7.1), openWakeWord (1.10.0), Matter Server (8.1.0), Govee to MQTT Bridge (2025.04.13-17d43d72)
```

### Anything in the add-on logs that might be useful for us?

```txt

```

**Comment by Xebozone** [comment]
Should hopefully be fixed with https://github.com/home-assistant/addons/pull/4126
Thanks for your patience.
Note: Certificate changes do sometimes require a restart of Home Assistant. Unfortunately, I don't think that's in the DuckDNS AddOn's control.

**Comment by franky1808** [comment]
Any idea when this will be rolled out? :-)

**Comment by Xebozone** [comment]
Not sure, sorry! It depends on the maintainers of the project to review and approve the PR, then it will shortly be rolled-out when you check for updates in AddOns in HA.

From what I can see though, usually within 24-48 hours, so, hopefully a maintainer will review it soon.

**Comment by Xebozone** [comment]
> Any idea when this will be rolled out? :-)

Just rolled out 🥳

**Comment by franky1808** [comment]
Thanks for the update! Yay! 🥳

Hey @agners, please relax. My problem is not solved yet as it is not working yet. 
I probably need to redo the configuration - but so far it's still dead in the water. I'll close when solved. ❤️🙂

**Comment by Xebozone** [comment]
Let me know if you still need help. I'm monitoring this thread.
Try restart your HA OS/VM first, as sometimes that's needed for certificate updates.

**Comment by franky1808** [comment]
Thanks for keeping an eye on this thread and monitoring it. 😃  I really appreciate it! 🥇 

So, I'm finally back on my instance from outside, but unfortunately my configuration got a bit messed up after the two updates. So it works 🥳 

However, I now have a “CSRF_TRUSTED_ORIGINS” error in some add-ons and integrations since DuckDNS broke down. 
I don't know yet whether it's due to the add-ons or DuckDNS / NGINX – and where exactly the problem lies. 
Unless something has been changed in the core, I would probably have noticed it. 

Since at least DuckDNS is working again in the core, I would close the ticket and continue searching. UNLESS you have another idea or hint. 
I think I read something about DuckDNS and CSRF in the last few days, but I can't find it anymore. But I could also be wrong. I've read too many threads in the last few days. :-)

**Comment by Xebozone** [comment]
> Thanks for keeping an eye on this thread and monitoring it. 😃 I really appreciate it! 🥇
> 
> So, I'm finally back on my instance from outside, but unfortunately my configuration got a bit messed up after the two updates. So it works 🥳
> 
> However, I now have a “CSRF_TRUSTED_ORIGINS” error in some add-ons and integrations since DuckDNS broke down. I don't know yet whether it's due to the add-ons or DuckDNS / NGINX – and where exactly the problem lies. Unless something has been changed in the core, I would probably have noticed it.
> 
> Since at least DuckDNS is working again in the core, I would close the ticket and continue searching. UNLESS you have another idea or hint. I think I read something about DuckDNS and CSRF in the last few days, but I can't find it anymore. But I could also be wrong. I've read too many threads in the last few days. :-)

Thanks for closing this.
DuckDNS doesn't touch your main HA config, so, there may be something else going on.
I did a quick Google of Home Assistant and CSRF_TRUSTED_ORIGINS and got lots of matches for something called Babybuddy...
It sounds like something related to an add-on you're using.

I would suggest trying to reboot your HA VM or OS and seeing if that helps.
Also, make sure you're accessing HA with the correct URL.
Good luck.

**Comment by peter-mc** [comment]
Seems to be a problem with the entire duckdns site, there is a banner on the site saying its down.

<img width="1194" height="610" alt="Image" src="https://github.com/user-attachments/assets/d1989d77-a8a6-4752-a332-c609031c9d9b" />

**Comment by Xebozone** [comment]
Thanks @peter-mc 
Yes, it was down from yesterday. When the issue was created the site was up, but indeed, DuckDNS does sometimes go down and that can cause issues.
